"""Generator functions for /etc configuration files (M15).

Every function returns ``bytes`` (UTF-8 encoded text) so callers can write
them directly to the rootfs staging directory without charset complications.

All outputs use ``\n`` line endings (UNIX).
"""

from __future__ import annotations


def make_passwd(extra_users: list[dict] | None = None) -> bytes:
    """Generate ``/etc/passwd``.

    Includes root and nobody.  *extra_users* items must have keys:
    ``name``, ``uid``, ``gid``, ``home``, ``shell``, and optionally
    ``comment``.
    """
    lines = [
        "root:x:0:0:root:/root:/bin/sh",
        "daemon:x:1:1:daemon:/usr/sbin:/bin/false",
        "nobody:x:65534:65534:nobody:/nonexistent:/bin/false",
    ]
    for u in extra_users or []:
        lines.append(
            "{name}:x:{uid}:{gid}:{comment}:{home}:{shell}".format(
                name=u["name"],
                uid=u["uid"],
                gid=u["gid"],
                comment=u.get("comment", u["name"]),
                home=u.get("home", f"/home/{u['name']}"),
                shell=u.get("shell", "/bin/sh"),
            )
        )
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_group(extra_groups: list[dict] | None = None) -> bytes:
    """Generate ``/etc/group``."""
    lines = [
        "root:x:0:",
        "daemon:x:1:",
        "tty:x:5:",
        "disk:x:6:",
        "wheel:x:10:root",
        "users:x:100:",
        "nobody:x:65534:",
    ]
    for g in extra_groups or []:
        members = ",".join(g.get("members", []))
        lines.append(f"{g['name']}:x:{g['gid']}:{members}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_shadow() -> bytes:
    """Generate ``/etc/shadow`` with locked root and nobody accounts."""
    lines = [
        "root:!:0:0:99999:7:::",
        "daemon:!:0:0:99999:7:::",
        "nobody:!:0:0:99999:7:::",
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_hosts(hostname: str) -> bytes:
    """Generate ``/etc/hosts``."""
    return (
        f"127.0.0.1  localhost\n"
        f"127.0.1.1  {hostname}\n"
        f"::1        localhost ip6-localhost ip6-loopback\n"
    ).encode()


def make_hostname(hostname: str) -> bytes:
    """Generate ``/etc/hostname``."""
    return (hostname + "\n").encode("utf-8")


def make_fstab(extra_mounts: list[dict] | None = None) -> bytes:
    """Generate ``/etc/fstab``.

    Standard proc/sys/devtmpfs entries are always included.
    *extra_mounts* items must have keys:
    ``device``, ``mountpoint``, ``fstype``, ``options``, ``dump``, ``pass``.
    """
    lines = [
        "# <file system>  <mount point>  <type>    <options>       <dump>  <pass>",
        "proc             /proc          proc      defaults        0       0",
        "sysfs            /sys           sysfs     defaults        0       0",
        "devtmpfs         /dev           devtmpfs  defaults        0       0",
        "tmpfs            /tmp           tmpfs     defaults,nosuid 0       0",
        "tmpfs            /run           tmpfs     defaults,nosuid 0       0",
    ]
    for m in extra_mounts or []:
        lines.append(
            "{device:<16} {mountpoint:<14} {fstype:<9} {options:<15} {dump}       {pass_}".format(
                device=m["device"],
                mountpoint=m["mountpoint"],
                fstype=m["fstype"],
                options=m.get("options", "defaults"),
                dump=m.get("dump", 0),
                pass_=m.get("pass", 0),
            )
        )
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_profile(extra_paths: list[str] | None = None) -> bytes:
    """Generate ``/etc/profile``."""
    paths = ["/usr/local/sbin", "/usr/local/bin", "/usr/sbin", "/usr/bin", "/sbin", "/bin"]
    paths.extend(extra_paths or [])
    path_str = ":".join(paths)
    return (
        "# /etc/profile — system-wide shell init\n"
        f'export PATH="{path_str}"\n'
        'export PS1="[\\u@\\h \\W]\\$ "\n'
        "umask 022\n"
        "\n"
        "for f in /etc/profile.d/*.sh; do\n"
        '  [ -r "$f" ] && . "$f"\n'
        "done\n"
    ).encode()


def make_shells() -> bytes:
    """Generate ``/etc/shells``."""
    return ("# /etc/shells — valid login shells\n/bin/sh\n/bin/ash\n/bin/bash\n").encode()


def make_nsswitch_conf() -> bytes:
    """Generate ``/etc/nsswitch.conf``."""
    return (
        b"passwd:   files\ngroup:    files\nshadow:   files\nhosts:    files dns\nnetworks: files\n"
    )


def make_resolv_conf(nameservers: list[str] | None = None) -> bytes:
    """Generate ``/etc/resolv.conf``."""
    servers = nameservers or ["8.8.8.8", "1.1.1.1"]
    lines = ["# /etc/resolv.conf — generated by osfabricum"]
    for ns in servers:
        lines.append(f"nameserver {ns}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_os_release(
    distribution: str,
    version: str = "dev",
    pretty_name: str | None = None,
) -> bytes:
    """Generate ``/etc/os-release``."""
    name = distribution.upper()
    pretty = pretty_name or f"{name} {version}"
    return (
        f'NAME="{name}"\n'
        f'VERSION="{version}"\n'
        f"ID={distribution.lower()}\n"
        f'PRETTY_NAME="{pretty}"\n'
        'HOME_URL="https://github.com/4stm4/osfabricum"\n'
    ).encode()
