"""Init system skeleton generators (M15).

Supports two init systems:
* ``"busybox"`` — BusyBox ``/sbin/init`` + ``/etc/inittab`` + ``/etc/init.d/rcS``
* ``"systemd"`` — stub multi-user.target structure (binaries installed in M16)

Each generator writes files into an existing staging rootfs directory and
returns the list of relative paths it created.
"""

from __future__ import annotations

from pathlib import Path

# ---------------------------------------------------------------------------
# BusyBox init
# ---------------------------------------------------------------------------

_INITTAB = """\
# /etc/inittab — BusyBox init configuration
# Format: <id>:<runlevels>:<action>:<process>

::sysinit:/etc/init.d/rcS

# Primary console
console::respawn:/sbin/getty -L console 115200 vt100

# Serial console (common on embedded boards)
ttyAMA0::respawn:/sbin/getty -L ttyAMA0 115200 vt100
ttyS0::respawn:/sbin/getty -L ttyS0 115200 vt100

::ctrlaltdel:/sbin/reboot
::shutdown:/sbin/swapoff -a
::shutdown:/bin/umount -a -r
::restart:/sbin/init
"""

_RCS = """\
#!/bin/sh
# /etc/init.d/rcS — System initialisation script (BusyBox)
# Generated by osfabricum — do not edit manually.

# Mount virtual filesystems
mount -t proc     proc     /proc
mount -t sysfs    sysfs    /sys
mount -t devtmpfs devtmpfs /dev 2>/dev/null || true
mount -t tmpfs    tmpfs    /tmp
mount -t tmpfs    tmpfs    /run

mkdir -p /dev/pts /dev/shm
mount -t devpts devpts /dev/pts

# Set hostname
if [ -f /etc/hostname ]; then
    hostname "$(cat /etc/hostname)"
fi

# Bring up loopback interface
ip link set lo up 2>/dev/null || true

# Run first-boot tasks (if any)
if [ -d /etc/osfab-firstboot.d ]; then
    for script in /etc/osfab-firstboot.d/*.sh; do
        [ -x "$script" ] && "$script"
    done
fi

# Run service scripts
for script in /etc/init.d/S[0-9][0-9]*; do
    [ -x "$script" ] && "$script" start
done
"""


def setup_busybox_init(stage_dir: Path) -> list[str]:
    """Write BusyBox init configuration into *stage_dir*.

    Returns a list of relative paths written.
    """
    written: list[str] = []

    inittab = stage_dir / "etc" / "inittab"
    inittab.write_text(_INITTAB, encoding="utf-8")
    written.append("etc/inittab")

    rcs = stage_dir / "etc" / "init.d" / "rcS"
    rcs.write_text(_RCS, encoding="utf-8")
    rcs.chmod(0o755)
    written.append("etc/init.d/rcS")

    return written


# ---------------------------------------------------------------------------
# systemd stub
# ---------------------------------------------------------------------------

_SYSTEMD_DIRS = [
    "etc/systemd",
    "etc/systemd/system",
    "etc/systemd/system/multi-user.target.wants",
    "etc/systemd/system/sysinit.target.wants",
    "lib/systemd",
    "lib/systemd/system",
    "usr/lib/systemd",
    "usr/lib/systemd/system",
]

_BASIC_TARGET = """\
[Unit]
Description=Basic System
Documentation=man:systemd.special(7)
Requires=sysinit.target
After=sysinit.target
AllowIsolate=yes
"""

_MULTI_USER_TARGET = """\
[Unit]
Description=Multi-User System
Documentation=man:systemd.special(7)
Requires=basic.target
Conflicts=rescue.service rescue.target
After=basic.target rescue.service rescue.target
AllowIsolate=yes
"""


def setup_systemd_init(stage_dir: Path) -> list[str]:
    """Write systemd stub configuration into *stage_dir*.

    The actual systemd binaries are installed in M16; this only creates
    the configuration skeleton.

    Returns a list of relative paths written.
    """
    written: list[str] = []

    for d in _SYSTEMD_DIRS:
        (stage_dir / d).mkdir(parents=True, exist_ok=True)

    unit_dir = stage_dir / "usr" / "lib" / "systemd" / "system"

    basic = unit_dir / "basic.target"
    basic.write_text(_BASIC_TARGET, encoding="utf-8")
    written.append("usr/lib/systemd/system/basic.target")

    multi = unit_dir / "multi-user.target"
    multi.write_text(_MULTI_USER_TARGET, encoding="utf-8")
    written.append("usr/lib/systemd/system/multi-user.target")

    # default.target symlink → multi-user.target
    default_link = unit_dir / "default.target"
    if not default_link.exists():
        default_link.symlink_to("multi-user.target")
    written.append("usr/lib/systemd/system/default.target")

    return written


# ---------------------------------------------------------------------------
# Dispatcher
# ---------------------------------------------------------------------------


def setup_init_system(stage_dir: Path, init_system: str) -> list[str]:
    """Set up the named init system in *stage_dir*.

    Parameters
    ----------
    stage_dir:
        Rootfs staging directory.
    init_system:
        ``"busybox"`` or ``"systemd"``.

    Returns
    -------
    list[str]
        Relative paths of written files.

    Raises
    ------
    ValueError
        If *init_system* is not a known value.
    """
    if init_system == "busybox":
        return setup_busybox_init(stage_dir)
    if init_system == "systemd":
        return setup_systemd_init(stage_dir)
    raise ValueError(f"unknown init_system: {init_system!r}; choose 'busybox' or 'systemd'")
