"""hostapd package builder.

Downloads hostapd source, builds with nl80211 driver (needs libnl-3-dev and
libssl-dev which are installed inside the build container at build time),
bundles all shared-library dependencies found by ``ldd`` into the ``.ofpkg``
so the initramfs has everything it needs.

Also injects network-setup, hostapd start, and udhcpd start service scripts.

Entry point::

    from osfabricum.packaging.hostapd import build_hostapd
    result = build_hostapd(arch="aarch64", store_root=Path(...), db_url=...)
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import tarfile
import tempfile
import urllib.request
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

from sqlalchemy import select

from osfabricum.db.models import Artifact
from osfabricum.db.session import sync_session
from osfabricum.store.ingest import ingest_blob

HOSTAPD_VERSION = "2.10"
HOSTAPD_URL = f"https://w1.fi/releases/hostapd-{HOSTAPD_VERSION}.tar.gz"

_HOSTAPD_CONF = """\
# /etc/hostapd.conf — generated by osfabricum (tinywifi default)
# Change ssid/wpa_passphrase before deploying!

interface=wlan0
driver=nl80211
ssid=tinywifi
hw_mode=g
channel=6
ieee80211n=1
wmm_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0

# WPA2-PSK
wpa=2
wpa_passphrase=tinywifi123
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
"""

_UDHCPD_CONF = """\
# /etc/udhcpd.conf — DHCP server for wlan0 AP clients
start           192.168.42.10
end             192.168.42.100
interface       wlan0
max_leases      50
pidfile         /var/run/udhcpd.pid
option  subnet  255.255.255.0
option  router  192.168.42.1
option  dns     8.8.8.8 1.1.1.1
"""

_S40_NETWORK = """\
#!/bin/sh
# /etc/init.d/S40network — Configure wlan0 for AP mode

AP_IFACE=wlan0
AP_ADDR=192.168.42.1
AP_PREFIX=24

case "$1" in
start)
    ip link set lo up 2>/dev/null || true
    ip link set "$AP_IFACE" up 2>/dev/null || true
    ip addr flush dev "$AP_IFACE" 2>/dev/null || true
    ip addr add "$AP_ADDR/$AP_PREFIX" dev "$AP_IFACE" 2>/dev/null || true
    echo 1 > /proc/sys/net/ipv4/ip_forward
    ;;
stop)
    ip addr flush dev "$AP_IFACE" 2>/dev/null || true
    ;;
esac
"""

_S60_HOSTAPD = """\
#!/bin/sh
# /etc/init.d/S60hostapd — Start hostapd WiFi access point

CONF=/etc/hostapd.conf
PIDFILE=/var/run/hostapd.pid

case "$1" in
start)
    mkdir -p /var/run
    hostapd -B -P "$PIDFILE" "$CONF" 2>/var/log/hostapd.log || true
    ;;
stop)
    kill "$(cat $PIDFILE 2>/dev/null)" 2>/dev/null || true
    ;;
restart)
    "$0" stop; sleep 1; "$0" start
    ;;
esac
"""

_S70_UDHCPD = """\
#!/bin/sh
# /etc/init.d/S70udhcpd — Start udhcpd DHCP server for AP clients

CONF=/etc/udhcpd.conf
PIDFILE=/var/run/udhcpd.pid

case "$1" in
start)
    mkdir -p /var/run
    udhcpd "$CONF" 2>/var/log/udhcpd.log || true
    ;;
stop)
    kill "$(cat $PIDFILE 2>/dev/null)" 2>/dev/null || true
    ;;
restart)
    "$0" stop; sleep 1; "$0" start
    ;;
esac
"""

# hostapd .config — nl80211 driver + WPA2 + 11n support
_HOSTAPD_BUILD_CONFIG = """\
CONFIG_DRIVER_NL80211=y
CONFIG_LIBNL32=y
CONFIG_TLS=openssl
CONFIG_IEEE80211N=y
CONFIG_IEEE80211AC=y
CONFIG_WPA_TRACE=
CONFIG_WPA_TRACE_BFD=
CONFIG_SAE=y
CONFIG_OWE=y
CONFIG_SUITEB=y
CONFIG_IEEE80211R=y
CONFIG_IAPP=
CONFIG_RSSI_STATS=y
CONFIG_CTRL_IFACE=y
CONFIG_CTRL_IFACE_UNIX=y
CONFIG_HOSTAPD=y
"""


@dataclass
class HostapdBuildResult:
    success: bool
    artifact_id: str | None = None
    error: str | None = None
    logs: list[str] = field(default_factory=list)
    cache_hit: bool = False


def _store_key(arch: str) -> str:
    return f"packages/hostapd/{HOSTAPD_VERSION}/{arch}/hostapd.ofpkg"


def _run(cmd: list[str], *, cwd: Path, logs: list[str], extra_env: dict | None = None) -> None:
    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    proc = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, env=env)
    for line in proc.stdout.splitlines()[-30:]:
        logs.append(f"  {line}")
    if proc.returncode != 0:
        for line in proc.stderr.splitlines()[-60:]:
            logs.append(f"  ERR: {line}")
        raise RuntimeError(f"{cmd[0]} exited {proc.returncode}")


def _install_build_deps(logs: list[str]) -> None:
    """Ensure libnl-3-dev and libnl-genl-3-dev are available in the container."""
    # Check if already installed (avoid slow apt-get if possible)
    logs.append("[hostapd] running apt-get update…")
    subprocess.run(
        ["apt-get", "update", "-qq"],
        capture_output=True, text=True,
        env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
    )
    logs.append("[hostapd] installing build dependencies via apt-get…")
    proc = subprocess.run(
        ["apt-get", "install", "-y", "--no-install-recommends",
         "pkg-config", "libnl-3-dev", "libnl-genl-3-dev", "libssl-dev"],
        capture_output=True, text=True,
        env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
    )
    if proc.returncode != 0:
        raise RuntimeError(f"apt-get install failed:\n{proc.stderr[-500:]}")
    logs.append("[hostapd] build deps installed")


def _copy_dynamic_deps(binary: Path, destdir: Path, logs: list[str]) -> None:
    """Use ldd to discover shared-library deps and copy them into destdir."""
    proc = subprocess.run(["ldd", str(binary)], capture_output=True, text=True)
    copied: set[str] = set()
    for line in proc.stdout.splitlines():
        # "libname.so.x => /path/to/libname.so.x (0xaddr)"
        m = re.search(r"=>\s+(/[^\s]+\.so[^\s]*)", line)
        if m:
            src = Path(m.group(1))
            if src.exists() and str(src) not in copied:
                rel = src.relative_to("/")
                dst = destdir / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                copied.add(str(src))
                logs.append(f"[hostapd] bundled: {src}")
        # "/lib/ld-linux-aarch64.so.1 (0xaddr)"
        m2 = re.match(r"\s+(/[^\s]+ld-linux[^\s]+)\s+\(", line)
        if m2:
            src = Path(m2.group(1).strip())
            if src.exists() and str(src) not in copied:
                rel = src.relative_to("/")
                dst = destdir / rel
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)
                copied.add(str(src))
                logs.append(f"[hostapd] bundled ld: {src}")


def _pack_ofpkg(destdir: Path, arch: str) -> bytes:
    files_buf = io.BytesIO()
    with tarfile.open(fileobj=files_buf, mode="w:gz") as tar:
        for item in sorted(destdir.rglob("*"), key=lambda p: str(p.relative_to(destdir))):
            rel = str(item.relative_to(destdir))
            if item.is_symlink():
                info = tarfile.TarInfo(name=rel)
                info.type = tarfile.SYMTYPE
                info.linkname = str(item.readlink())
                info.mtime = 0
                tar.addfile(info)
            elif item.is_dir():
                info = tarfile.TarInfo(name=rel)
                info.type = tarfile.DIRTYPE
                info.mode = 0o755
                info.mtime = 0
                tar.addfile(info)
            elif item.is_file():
                data = item.read_bytes()
                info = tarfile.TarInfo(name=rel)
                info.size = len(data)
                info.mode = item.stat().st_mode & 0o777
                info.mtime = 0
                tar.addfile(info, io.BytesIO(data))
    files_tar = files_buf.getvalue()

    def _sha256(b: bytes) -> str:
        return hashlib.sha256(b).hexdigest()

    manifest = {
        "format_version": "1",
        "name": "hostapd",
        "version": HOSTAPD_VERSION,
        "arch": arch,
        "description": "hostapd — IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP Authenticator",
        "license": "BSD-3-Clause",
        "dependencies": [],
        "build_system": "make",
    }
    manifest_bytes = json.dumps(manifest, indent=2, sort_keys=True).encode()
    sbom = json.dumps({
        "bomFormat": "CycloneDX", "specVersion": "1.4",
        "components": [{"name": "hostapd", "version": HOSTAPD_VERSION}],
    }, indent=2).encode()
    checksums = (
        f"{_sha256(manifest_bytes)}  manifest.json\n"
        f"{_sha256(files_tar)}  files.tar.gz\n"
        f"{_sha256(sbom)}  sbom.json\n"
    ).encode()

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", manifest_bytes)
        zf.writestr("files.tar.gz", files_tar)
        zf.writestr("checksums.sha256", checksums)
        zf.writestr("sbom.json", sbom)
    return zip_buf.getvalue()


def build_hostapd(
    *,
    arch: str,
    store_root: Path,
    db_url: str | None = None,
    jobs: int = 1,
) -> HostapdBuildResult:
    """Build hostapd with nl80211 driver and ingest as a package artifact."""
    logs: list[str] = []
    store_key = _store_key(arch)

    if db_url is not None:
        with sync_session(db_url) as session:
            existing = session.scalar(select(Artifact).where(Artifact.store_key == store_key))
            if existing is not None:
                logs.append(f"[hostapd] cache hit: {existing.id[:8]}")
                return HostapdBuildResult(
                    success=True, artifact_id=existing.id, logs=logs, cache_hit=True
                )

    try:
        _install_build_deps(logs)
    except Exception as exc:
        return HostapdBuildResult(success=False, error=f"dep install failed: {exc}", logs=logs)

    local_tarball = Path(f"/tmp/hostapd-{HOSTAPD_VERSION}.tar.gz")
    if local_tarball.exists() and local_tarball.stat().st_size > 100_000:
        logs.append(f"[hostapd] using pre-downloaded {local_tarball}")
        tarball = local_tarball.read_bytes()
    else:
        logs.append(f"[hostapd] downloading {HOSTAPD_URL}")
        try:
            req = urllib.request.Request(HOSTAPD_URL, headers={"User-Agent": "osfabricum/1.0"})
            with urllib.request.urlopen(req, timeout=600) as resp:
                tarball = resp.read()
        except Exception as exc:
            return HostapdBuildResult(success=False, error=f"download failed: {exc}", logs=logs)

    logs.append(f"[hostapd] downloaded {len(tarball)} bytes")
    tmp = tempfile.mkdtemp(prefix="osfab-hostapd-")
    try:
        with tarfile.open(fileobj=io.BytesIO(tarball), mode="r:gz") as tar:
            tar.extractall(path=tmp, filter="data")
        entries = list(Path(tmp).iterdir())
        top = entries[0] if len(entries) == 1 and entries[0].is_dir() else Path(tmp)
        src_dir = top / "hostapd"
        logs.append(f"[hostapd] extracted to {src_dir}")

        # Write build config
        (src_dir / ".config").write_text(_HOSTAPD_BUILD_CONFIG)

        logs.append(f"[hostapd] compiling with -j{jobs}…")
        _run(
            ["make", f"-j{jobs}"],
            cwd=src_dir, logs=logs,
            extra_env={"EXTRA_CFLAGS": "-Os -Wno-error"},
        )

        # ---- install ----
        destdir = Path(tmp) / "destdir"
        (destdir / "usr" / "sbin").mkdir(parents=True)
        (destdir / "etc" / "init.d").mkdir(parents=True)
        (destdir / "var" / "log").mkdir(parents=True)
        (destdir / "var" / "run").mkdir(parents=True)

        shutil.copy2(src_dir / "hostapd", destdir / "usr" / "sbin" / "hostapd")
        (destdir / "usr" / "sbin" / "hostapd").chmod(0o755)
        if (src_dir / "hostapd_cli").exists():
            shutil.copy2(src_dir / "hostapd_cli", destdir / "usr" / "sbin" / "hostapd_cli")
            (destdir / "usr" / "sbin" / "hostapd_cli").chmod(0o755)

        # Bundle all shared-library dependencies
        _copy_dynamic_deps(destdir / "usr" / "sbin" / "hostapd", destdir, logs)

        # Config files
        (destdir / "etc" / "hostapd.conf").write_text(_HOSTAPD_CONF)
        (destdir / "etc" / "udhcpd.conf").write_text(_UDHCPD_CONF)

        # Init service scripts
        for name, content in [
            ("S40network", _S40_NETWORK),
            ("S60hostapd", _S60_HOSTAPD),
            ("S70udhcpd", _S70_UDHCPD),
        ]:
            p = destdir / "etc" / "init.d" / name
            p.write_text(content)
            p.chmod(0o755)

        logs.append(f"[hostapd] installed to {destdir}")

        ofpkg_data = _pack_ofpkg(destdir, arch)
        logs.append(f"[hostapd] packaged {len(ofpkg_data)} bytes")

        artifact = ingest_blob(
            data=ofpkg_data,
            store_root=store_root,
            store_key=store_key,
            kind="package",
            name="hostapd",
            version=HOSTAPD_VERSION,
            arch=arch,
            media_type="application/zip",
            db_url=db_url,
            retention_class="permanent",
            input_hash=hashlib.sha256(tarball).hexdigest(),
        )
        logs.append(f"[hostapd] artifact ingested: {artifact.id}")
        return HostapdBuildResult(success=True, artifact_id=artifact.id, logs=logs)

    except Exception as exc:
        return HostapdBuildResult(success=False, error=str(exc), logs=logs)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
