"""tinywifi-web package builder.

Clones https://github.com/4stm4/tinyWiFi, builds the ``tinywifi-web``
binary (static aarch64-musl) and packages it as a ``.ofpkg`` artifact.

Also injects:
  - /etc/tinywifi/web.toml      — tinywifi-web config
  - /etc/init.d/S80tinywifi-web — BusyBox init boot script
  - /etc/init.d/tinywifi-web    — service-control script (for the web panel itself)

Entry point::

    from osfabricum.packaging.tinywifi import build_tinywifi
    result = build_tinywifi(arch="aarch64", store_root=Path(...), db_url=...)
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import shutil
import subprocess
import tarfile
import tempfile
import urllib.request
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

from sqlalchemy import select

from osfabricum.db.models import Artifact
from osfabricum.db.session import sync_session
from osfabricum.store.ingest import ingest_blob
from osfabricum.packaging.registry import register

TINYWIFI_REPO = "https://github.com/4stm4/tinyWiFi"
TINYWIFI_VERSION = "git-main"

_STORE_KEY_VERSION = "1"

_WEB_TOML = """\
# /etc/tinywifi/web.toml — generated by osfabricum (tinywifi)

[web]
listen = "0.0.0.0:80"

[display]
refresh_secs = 5

[paths]
hostapd_conf  = "/etc/hostapd.conf"
nanodhcp_conf = "/etc/nanodhcp/nanodhcp.conf"
leases_file   = "/var/lib/nanodhcp/leases"

[services]
hostapd      = "hostapd"
nanodhcp     = "nanodhcp"
web          = "tinywifi-web"
"""

_S80_TINYWIFI_WEB = """\
#!/bin/sh
# /etc/init.d/S80tinywifi-web — Start tinywifi-web management panel

CONF=/etc/tinywifi/web.toml
PIDFILE=/run/tinywifi-web.pid

case "$1" in
start)
    mkdir -p /run /var/log
    TINYWIFI_CONFIG="$CONF" start-stop-daemon --start --quiet --background \
        --pidfile "$PIDFILE" --make-pidfile \
        --exec /usr/sbin/tinywifi-web 2>/var/log/tinywifi-web.log || true
    ;;
stop)
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" 2>/dev/null || true
    rm -f "$PIDFILE"
    ;;
restart|reload)
    "$0" stop; sleep 1; "$0" start
    ;;
esac
"""

# Service-control script (no S## prefix — used by the panel itself)
_TINYWIFI_WEB_SVC = """\
#!/bin/sh
# /etc/init.d/tinywifi-web — service control for tinywifi-web

CONF=/etc/tinywifi/web.toml
PIDFILE=/run/tinywifi-web.pid

case "$1" in
start)
    mkdir -p /run /var/log
    TINYWIFI_CONFIG="$CONF" start-stop-daemon --start --quiet --background \
        --pidfile "$PIDFILE" --make-pidfile \
        --exec /usr/sbin/tinywifi-web 2>/var/log/tinywifi-web.log || true
    ;;
stop)
    start-stop-daemon --stop --quiet --pidfile "$PIDFILE" 2>/dev/null || true
    rm -f "$PIDFILE"
    ;;
restart|reload)
    "$0" stop; sleep 1; "$0" start
    ;;
status)
    [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null \
        && echo "tinywifi-web running" || echo "tinywifi-web stopped"
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
"""


@dataclass
class TinywifiBuildResult:
    success: bool
    artifact_id: str | None = None
    error: str | None = None
    logs: list[str] = field(default_factory=list)
    cache_hit: bool = False


def _store_key(arch: str) -> str:
    return f"packages/tinywifi-web/{TINYWIFI_VERSION}-v{_STORE_KEY_VERSION}/{arch}/tinywifi-web.ofpkg"


def _run(cmd: list[str], *, cwd: Path, logs: list[str], extra_env: dict | None = None) -> None:
    env = os.environ.copy()
    if extra_env:
        env.update(extra_env)
    proc = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, env=env)
    for line in proc.stdout.splitlines()[-20:]:
        logs.append(f"  {line}")
    if proc.returncode != 0:
        for line in proc.stderr.splitlines()[-40:]:
            logs.append(f"  ERR: {line}")
        raise RuntimeError(f"{cmd[0]} exited {proc.returncode}")


def _ensure_rust(logs: list[str]) -> dict[str, str]:
    """Install rustup + musl target if not already present. Returns extra env."""
    cargo_bin = Path("/root/.cargo/bin")
    cargo_exe = cargo_bin / "cargo"

    if not cargo_exe.exists():
        logs.append("[tinywifi] installing rustup…")
        subprocess.run(
            ["apt-get", "install", "-y", "--no-install-recommends",
             "curl", "git", "musl-tools"],
            capture_output=True, text=True,
            env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
        )
        rustup_sh = Path("/tmp/rustup-init.sh")
        with urllib.request.urlopen("https://sh.rustup.rs", timeout=120) as r:
            rustup_sh.write_bytes(r.read())
        subprocess.run(
            ["sh", str(rustup_sh), "-y", "--no-modify-path",
             "--default-toolchain", "stable", "--profile", "minimal"],
            env={**os.environ, "HOME": "/root"},
            check=True, capture_output=True,
        )
        logs.append("[tinywifi] rustup installed")
    else:
        logs.append("[tinywifi] cargo already present")
        subprocess.run(
            ["apt-get", "install", "-y", "--no-install-recommends", "git", "musl-tools"],
            capture_output=True, text=True,
            env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
        )

    new_path = f"{cargo_bin}:{os.environ.get('PATH', '')}"
    rustup_exe = str(cargo_bin / "rustup")

    logs.append("[tinywifi] adding aarch64-unknown-linux-musl target…")
    subprocess.run(
        [rustup_exe, "target", "add", "aarch64-unknown-linux-musl"],
        env={**os.environ, "PATH": new_path, "HOME": "/root"},
        capture_output=True,
    )

    return {"PATH": new_path, "HOME": "/root"}


def _pack_ofpkg(destdir: Path, arch: str) -> bytes:
    files_buf = io.BytesIO()
    with tarfile.open(fileobj=files_buf, mode="w:gz") as tar:
        for item in sorted(destdir.rglob("*"), key=lambda p: str(p.relative_to(destdir))):
            rel = str(item.relative_to(destdir))
            if item.is_symlink():
                info = tarfile.TarInfo(name=rel)
                info.type = tarfile.SYMTYPE
                info.linkname = str(item.readlink())
                info.mtime = 0
                tar.addfile(info)
            elif item.is_dir():
                info = tarfile.TarInfo(name=rel)
                info.type = tarfile.DIRTYPE
                info.mode = 0o755
                info.mtime = 0
                tar.addfile(info)
            elif item.is_file():
                data = item.read_bytes()
                info = tarfile.TarInfo(name=rel)
                info.size = len(data)
                info.mode = item.stat().st_mode & 0o777
                info.mtime = 0
                tar.addfile(info, io.BytesIO(data))
    files_tar = files_buf.getvalue()

    def _sha256(b: bytes) -> str:
        return hashlib.sha256(b).hexdigest()

    manifest = {
        "format_version": "1",
        "name": "tinywifi-web",
        "version": TINYWIFI_VERSION,
        "arch": arch,
        "description": "tinywifi-web — WiFi AP management web panel",
        "license": "AGPL-3.0",
        "dependencies": ["nanodhcp", "hostapd"],
        "build_system": "cargo",
    }
    manifest_bytes = json.dumps(manifest, indent=2, sort_keys=True).encode()
    sbom = json.dumps({
        "bomFormat": "CycloneDX", "specVersion": "1.4",
        "components": [{"name": "tinywifi-web", "version": TINYWIFI_VERSION}],
    }, indent=2).encode()
    checksums = (
        f"{_sha256(manifest_bytes)}  manifest.json\n"
        f"{_sha256(files_tar)}  files.tar.gz\n"
        f"{_sha256(sbom)}  sbom.json\n"
    ).encode()

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("manifest.json", manifest_bytes)
        zf.writestr("files.tar.gz", files_tar)
        zf.writestr("checksums.sha256", checksums)
        zf.writestr("sbom.json", sbom)
    return zip_buf.getvalue()


@register("webui-agent")
def build_tinywifi(
    *,
    arch: str,
    store_root: Path,
    db_url: str | None = None,
    jobs: int = 1,
) -> TinywifiBuildResult:
    """Clone tinyWiFi, build tinywifi-web static binary, ingest as package artifact."""
    logs: list[str] = []
    store_key = _store_key(arch)

    if db_url is not None:
        with sync_session(db_url) as session:
            existing = session.scalar(select(Artifact).where(Artifact.store_key == store_key))
            if existing is not None:
                logs.append(f"[tinywifi] cache hit: {existing.id[:8]}")
                return TinywifiBuildResult(
                    success=True, artifact_id=existing.id, logs=logs, cache_hit=True
                )

    try:
        rust_env = _ensure_rust(logs)
    except Exception as exc:
        return TinywifiBuildResult(success=False, error=f"rust install failed: {exc}", logs=logs)

    tmp = tempfile.mkdtemp(prefix="osfab-tinywifi-")
    try:
        src = Path(tmp) / "tinyWiFi"
        logs.append(f"[tinywifi] cloning {TINYWIFI_REPO}…")
        _run(["git", "clone", "--depth=1", TINYWIFI_REPO, str(src)],
             cwd=Path(tmp), logs=logs, extra_env=rust_env)

        logs.append("[tinywifi] building tinywifi-web (static aarch64-musl)…")
        _run(
            ["cargo", "build", "--release",
             "--target", "aarch64-unknown-linux-musl",
             "--bin", "tinywifi-web"],
            cwd=src, logs=logs,
            extra_env={
                **rust_env,
                "RUSTFLAGS": "-C target-feature=+crt-static",
                "CC_aarch64_unknown_linux_musl": "musl-gcc",
            },
        )

        binary = src / "target" / "aarch64-unknown-linux-musl" / "release" / "tinywifi-web"
        if not binary.exists():
            raise RuntimeError(f"binary not found at {binary}")

        destdir = Path(tmp) / "destdir"
        (destdir / "usr" / "sbin").mkdir(parents=True)
        (destdir / "etc" / "tinywifi").mkdir(parents=True)
        (destdir / "etc" / "init.d").mkdir(parents=True)
        (destdir / "var" / "log").mkdir(parents=True)
        (destdir / "run").mkdir(parents=True)

        shutil.copy2(binary, destdir / "usr" / "sbin" / "tinywifi-web")
        (destdir / "usr" / "sbin" / "tinywifi-web").chmod(0o755)
        logs.append(f"[tinywifi] binary size: {binary.stat().st_size} bytes")

        (destdir / "etc" / "tinywifi" / "web.toml").write_text(_WEB_TOML)

        boot_script = destdir / "etc" / "init.d" / "S80tinywifi-web"
        boot_script.write_text(_S80_TINYWIFI_WEB)
        boot_script.chmod(0o755)

        svc_script = destdir / "etc" / "init.d" / "tinywifi-web"
        svc_script.write_text(_TINYWIFI_WEB_SVC)
        svc_script.chmod(0o755)

        ofpkg_data = _pack_ofpkg(destdir, arch)
        logs.append(f"[tinywifi] packaged {len(ofpkg_data)} bytes")

        artifact = ingest_blob(
            data=ofpkg_data,
            store_root=store_root,
            store_key=store_key,
            kind="package",
            name="tinywifi-web",
            version=TINYWIFI_VERSION,
            arch=arch,
            media_type="application/zip",
            db_url=db_url,
            retention_class="permanent",
        )
        logs.append(f"[tinywifi] artifact ingested: {artifact.id}")
        return TinywifiBuildResult(success=True, artifact_id=artifact.id, logs=logs)

    except Exception as exc:
        return TinywifiBuildResult(success=False, error=str(exc), logs=logs)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
