"""Service installation into a rootfs staging directory (M16).

Two init systems are supported:

* ``"busybox"`` — writes a ``S??-<name>`` start/stop init.d script.
* ``"systemd"`` — writes a ``.service`` unit file and creates an
  ``enabled`` symlink in ``multi-user.target.wants/``.

``install_service_into_rootfs``
    Install a :class:`~osfabricum.db.models.Service` by name, loading its
    unit artifact from the store.

``install_services_into_rootfs``
    Install a list of service names.
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy import select

from osfabricum.db.models import Artifact, Service
from osfabricum.db.session import sync_session
from osfabricum.store.layout import blob_path

# ---------------------------------------------------------------------------
# BusyBox init.d stub template
# ---------------------------------------------------------------------------

_BUSYBOX_INITD_TEMPLATE = """\
#!/bin/sh
# /etc/init.d/{name} — auto-generated by osfabricum
# Description: {description}

DAEMON="{daemon}"
NAME="{name}"

start() {{
    echo "Starting $NAME..."
    $DAEMON &
}}

stop() {{
    echo "Stopping $NAME..."
    kill $(pidof "{name}") 2>/dev/null || true
}}

case "$1" in
    start)   start ;;
    stop)    stop ;;
    restart) stop; start ;;
    *)       echo "Usage: $0 {{start|stop|restart}}"; exit 1 ;;
esac
"""

# ---------------------------------------------------------------------------
# Systemd .service stub template
# ---------------------------------------------------------------------------

_SYSTEMD_SERVICE_TEMPLATE = """\
[Unit]
Description={description}
After=network.target

[Service]
Type=simple
ExecStart={daemon}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
"""


def _install_busybox_service(
    stage_dir: Path,
    name: str,
    description: str,
    daemon: str,
    order: int = 50,
    unit_data: bytes | None = None,
) -> str:
    """Install a BusyBox init.d script.  Returns relative path written."""
    initd_dir = stage_dir / "etc" / "init.d"
    initd_dir.mkdir(parents=True, exist_ok=True)

    script_name = f"S{order:02d}{name}"
    script_path = initd_dir / script_name

    if unit_data is not None:
        script_path.write_bytes(unit_data)
    else:
        content = _BUSYBOX_INITD_TEMPLATE.format(
            name=name,
            description=description,
            daemon=daemon,
        )
        script_path.write_text(content, encoding="utf-8")

    script_path.chmod(0o755)
    return f"etc/init.d/{script_name}"


def _install_systemd_service(
    stage_dir: Path,
    name: str,
    description: str,
    daemon: str,
    enabled: bool = True,
    unit_data: bytes | None = None,
) -> list[str]:
    """Install a systemd .service unit.  Returns list of relative paths."""
    unit_dir = stage_dir / "etc" / "systemd" / "system"
    unit_dir.mkdir(parents=True, exist_ok=True)

    service_file = unit_dir / f"{name}.service"
    if unit_data is not None:
        service_file.write_bytes(unit_data)
    else:
        content = _SYSTEMD_SERVICE_TEMPLATE.format(
            description=description,
            daemon=daemon,
        )
        service_file.write_text(content, encoding="utf-8")

    written = [f"etc/systemd/system/{name}.service"]

    if enabled:
        wants_dir = unit_dir / "multi-user.target.wants"
        wants_dir.mkdir(parents=True, exist_ok=True)
        symlink = wants_dir / f"{name}.service"
        if not symlink.exists():
            symlink.symlink_to(f"../{name}.service")
        written.append(f"etc/systemd/system/multi-user.target.wants/{name}.service")

    return written


def install_service_into_rootfs(
    service_name: str,
    stage_dir: Path,
    store_root: Path,
    *,
    init_system: str = "busybox",
    db_url: str | None = None,
    enabled: bool = True,
    order: int = 50,
) -> list[str]:
    """Install a named service from the DB into *stage_dir*.

    If the :class:`~osfabricum.db.models.Service` row has a
    ``unit_artifact_id``, the blob is loaded from the store and written as-is.
    Otherwise a stub unit is generated from the service name.

    Parameters
    ----------
    service_name:
        Name of the :class:`~osfabricum.db.models.Service` row.
    stage_dir:
        Rootfs staging directory.
    store_root:
        Artifact store root.
    init_system:
        ``"busybox"`` or ``"systemd"``.
    db_url:
        SQLAlchemy database URL.
    enabled:
        For systemd: create ``multi-user.target.wants/`` symlink.
    order:
        For BusyBox: numeric prefix for the ``S??-`` script name.

    Returns
    -------
    list[str]
        Relative paths written into *stage_dir*.
    """
    # Load Service row from DB (optional — falls back to stub if not found)
    unit_data: bytes | None = None
    description: str = service_name
    daemon: str = f"/usr/bin/{service_name}"
    db_init_system: str = init_system

    if db_url is not None:
        with sync_session(db_url) as session:
            svc: Service | None = session.scalar(
                select(Service).where(Service.name == service_name)
            )
            if svc is not None:
                db_init_system = svc.init_system
                if svc.unit_artifact_id is not None:
                    art: Artifact | None = session.scalar(
                        select(Artifact).where(Artifact.id == svc.unit_artifact_id)
                    )
                    if art is not None:
                        bp = blob_path(store_root, art.blob_sha256)
                        if bp.exists():
                            unit_data = bp.read_bytes()

    actual_init = db_init_system if db_init_system else init_system

    if actual_init == "busybox":
        path = _install_busybox_service(
            stage_dir, service_name, description, daemon, order, unit_data
        )
        return [path]
    if actual_init == "systemd":
        return _install_systemd_service(
            stage_dir, service_name, description, daemon, enabled, unit_data
        )
    raise ValueError(f"unknown init_system: {actual_init!r}")


def install_services_into_rootfs(
    service_names: list[str],
    stage_dir: Path,
    store_root: Path,
    *,
    init_system: str = "busybox",
    db_url: str | None = None,
) -> dict[str, list[str]]:
    """Install multiple services.

    Returns a mapping of ``service_name → [written paths]``.
    """
    result: dict[str, list[str]] = {}
    for i, name in enumerate(service_names):
        paths = install_service_into_rootfs(
            name,
            stage_dir,
            store_root,
            init_system=init_system,
            db_url=db_url,
            order=20 + i * 10,
        )
        result[name] = paths
    return result
