"""RPi boot partition file collection (M17).

Generates ``config.txt`` and ``cmdline.txt`` for the Raspberry Pi GPU
bootloader, and collects kernel / DTB / firmware blobs from the artifact
store into a plain ``{filename: bytes}`` mapping ready to be written to the
FAT boot partition.

``make_rpi_config_txt``
    Build a ``config.txt`` string for the given kernel and DTB filenames.

``make_cmdline_txt``
    Build a ``cmdline.txt`` string.

``collect_boot_files``
    Load kernel, DTB, and firmware blobs from the store by artifact ID.
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy import select

from osfabricum.db.models import Artifact
from osfabricum.db.session import sync_session
from osfabricum.store.layout import blob_path

# ---------------------------------------------------------------------------
# Config generators
# ---------------------------------------------------------------------------


def make_rpi_config_txt(
    *,
    kernel: str = "Image",
    dtb: str = "bcm2710-rpi-zero-2-w.dtb",
    enable_uart: bool = True,
    arm64: bool = True,
    initramfs: str | None = "initramfs.gz",
    extra: dict[str, str] | None = None,
) -> bytes:
    """Generate a ``config.txt`` for the RPi GPU firmware.

    Parameters
    ----------
    kernel:
        Filename of the Linux kernel image (e.g. ``"Image"``).
    dtb:
        Filename of the device tree blob.
    enable_uart:
        Set ``enable_uart=1`` for serial console output.
    arm64:
        Set ``arm_64bit=1`` for 64-bit mode (required for aarch64 kernels).
    initramfs:
        Filename of the initramfs cpio.gz.  When set, adds
        ``initramfs <name> followkernel`` to config.txt.  Pass ``None``
        to omit (for ext4 rootfs).
    extra:
        Additional ``key=value`` pairs appended at the end.

    Returns
    -------
    bytes
        UTF-8 encoded ``config.txt`` content.
    """
    lines = [
        "# config.txt — generated by osfabricum",
        f"kernel={kernel}",
        f"device_tree={dtb}",
    ]
    if arm64:
        lines.append("arm_64bit=1")
    if enable_uart:
        lines.append("enable_uart=1")
    if initramfs:
        lines.append(f"initramfs {initramfs} followkernel")
    for key, val in (extra or {}).items():
        lines.append(f"{key}={val}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def make_cmdline_txt(
    *,
    root: str | None = None,
    rootfstype: str | None = None,
    console: str = "serial0,115200",
    extra: list[str] | None = None,
) -> bytes:
    """Generate ``cmdline.txt`` kernel command line.

    When *root* is ``None`` (initramfs mode) the ``root=`` and
    ``rootfstype=`` parameters are omitted; the kernel boots directly
    from the initramfs image.

    Returns
    -------
    bytes
        A single line of space-separated kernel parameters, UTF-8 encoded.
    """
    params = [
        f"console={console}",
        "console=tty1",
    ]
    if root:
        params.append(f"root={root}")
    if rootfstype:
        params.append(f"rootfstype={rootfstype}")
    if root:
        params.append("rootwait")
    params.append("rw")
    params.extend(extra or [])
    return (" ".join(params) + "\n").encode("utf-8")


# ---------------------------------------------------------------------------
# Artifact loader
# ---------------------------------------------------------------------------


def _load_blob(artifact_id: str, store_root: Path, db_url: str | None) -> tuple[str, bytes]:
    """Load an artifact blob.  Returns ``(artifact.name, data)``."""
    with sync_session(db_url) as session:
        art: Artifact | None = session.scalar(select(Artifact).where(Artifact.id == artifact_id))
        if art is None:
            raise ValueError(f"artifact not found: {artifact_id!r}")
        name = art.name
        sha256 = art.blob_sha256

    bp = blob_path(store_root, sha256)
    if not bp.exists():
        raise FileNotFoundError(f"blob missing for artifact {artifact_id}: {bp}")

    return name, bp.read_bytes()


def collect_boot_files(
    *,
    kernel_artifact_id: str | None = None,
    firmware_artifact_ids: list[str] | None = None,
    dtb_artifact_ids: list[str] | None = None,
    store_root: Path,
    db_url: str | None = None,
    kernel_filename: str = "Image",
    extra_files: dict[str, bytes] | None = None,
    dtb_filename: str | None = None,
    arm64: bool = True,
    root_device: str | None = "/dev/mmcblk0p2",
    initramfs: str | None = None,
) -> dict[str, bytes]:
    """Collect all files that go into the FAT boot partition.

    Parameters
    ----------
    kernel_artifact_id:
        UUID of the kernel ``Artifact``.
    firmware_artifact_ids:
        List of firmware blob artifact UUIDs (``start4.elf``, ``fixup4.dat``, …).
    dtb_artifact_ids:
        List of DTB artifact UUIDs.
    store_root:
        Artifact store root.
    db_url:
        SQLAlchemy database URL.
    kernel_filename:
        How to name the kernel on the FAT partition (default: ``"Image"``).
    extra_files:
        Additional ``{filename: bytes}`` mappings merged last.
    dtb_filename:
        Override the DTB filename used in ``config.txt``.  If not given the
        name of the first DTB artifact is used.
    arm64:
        Pass ``arm_64bit=1`` into ``config.txt``.
    root_device:
        Root device written into ``cmdline.txt``.

    Returns
    -------
    dict[str, bytes]
        Mapping of filename → file bytes for every file to place in the
        boot partition.
    """
    files: dict[str, bytes] = {}

    # Kernel
    if kernel_artifact_id:
        _, kernel_data = _load_blob(kernel_artifact_id, store_root, db_url)
        files[kernel_filename] = kernel_data

    # DTBs
    first_dtb: str | None = dtb_filename
    for dtb_id in dtb_artifact_ids or []:
        name, data = _load_blob(dtb_id, store_root, db_url)
        # Use the artifact name as filename (strip path prefixes)
        dtb_fname = Path(name).name
        files[dtb_fname] = data
        if first_dtb is None:
            first_dtb = dtb_fname

    # Firmware blobs
    for fw_id in firmware_artifact_ids or []:
        name, data = _load_blob(fw_id, store_root, db_url)
        fw_fname = Path(name).name
        files[fw_fname] = data

    # config.txt
    files["config.txt"] = make_rpi_config_txt(
        kernel=kernel_filename,
        dtb=first_dtb or "bcm2710-rpi-zero-2-w.dtb",
        arm64=arm64,
        initramfs=initramfs,
    )

    # cmdline.txt
    files["cmdline.txt"] = make_cmdline_txt(root=root_device)

    # Extra files override everything
    files.update(extra_files or {})

    return files
