"""First-boot task installation (M11).

Scripts placed in ``/etc/osfab-firstboot.d/`` inside the rootfs are
executed once on first boot by a small init hook (not part of this module).
Each task entry describes one shell script to write.

``install_first_boot_tasks``
    Write tasks as numbered ``NN-<name>.sh`` scripts into
    ``{target_dir}/etc/osfab-firstboot.d/``.
"""

from __future__ import annotations

import stat
from pathlib import Path

_FIRSTBOOT_DIR = Path("etc") / "osfab-firstboot.d"

#: Header prepended to every generated first-boot script.
_SCRIPT_HEADER = """\
#!/bin/sh
# Auto-generated by osfabricum — do not edit manually.
# This script runs once on first boot.
set -e
"""


def install_first_boot_tasks(
    *,
    tasks: list[dict],
    target_dir: Path,
) -> list[Path]:
    """Write first-boot task scripts into the rootfs.

    Parameters
    ----------
    tasks:
        List of task dicts.  Each dict must have:

        * ``name`` (str) — short identifier used in the filename.
        * ``script`` (str) — shell script body.

        Optional keys:

        * ``order`` (int, default 50) — determines filename prefix
          (lower runs earlier).
        * ``description`` (str) — written as a comment in the script.

    target_dir:
        Rootfs root directory.

    Returns
    -------
    list[Path]
        Absolute paths of the written script files.
    """
    fb_dir = target_dir / _FIRSTBOOT_DIR
    fb_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    for task in tasks:
        name: str = task["name"]
        script_body: str = task["script"]
        order: int = int(task.get("order", 50))
        description: str = task.get("description", "")

        comment = f"# {description}\n" if description else ""
        content = f"{_SCRIPT_HEADER}{comment}{script_body}\n"

        filename = f"{order:02d}-{name}.sh"
        script_path = fb_dir / filename
        script_path.write_text(content, encoding="utf-8")

        # Make executable: rwxr-xr-x (0o755)
        script_path.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

        written.append(script_path)

    return written
